// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wr-49HfbXFF-LwKYG6iqLTkB0dPzfHM',
    appId: '1:352238551340:web:f962739bcaa8f596ea6c89',
    messagingSenderId: '352238551340',
    projectId: 'messaging-78cd1',
    authDomain: 'messaging-78cd1.firebaseapp.com',
    storageBucket: 'messaging-78cd1.appspot.com',
    measurementId: 'G-PTQ9FRLGT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPoyTC-w2FCnlY8pLf8pSlztqtSP0oao',
    appId: '1:352238551340:android:f25561d4a7731cd7ea6c89',
    messagingSenderId: '352238551340',
    projectId: 'messaging-78cd1',
    storageBucket: 'messaging-78cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZM7xgM2mLE4_N6yz8vBRhLnT3-WFdj8',
    appId: '1:352238551340:ios:cc5b3560d34843bdea6c89',
    messagingSenderId: '352238551340',
    projectId: 'messaging-78cd1',
    storageBucket: 'messaging-78cd1.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZM7xgM2mLE4_N6yz8vBRhLnT3-WFdj8',
    appId: '1:352238551340:ios:cc5b3560d34843bdea6c89',
    messagingSenderId: '352238551340',
    projectId: 'messaging-78cd1',
    storageBucket: 'messaging-78cd1.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5wr-49HfbXFF-LwKYG6iqLTkB0dPzfHM',
    appId: '1:352238551340:web:8963a176457adbf1ea6c89',
    messagingSenderId: '352238551340',
    projectId: 'messaging-78cd1',
    authDomain: 'messaging-78cd1.firebaseapp.com',
    storageBucket: 'messaging-78cd1.appspot.com',
    measurementId: 'G-C7D7WPF20T',
  );
}
